#!/bin/sh

echo "Activando proxy..." &&
export http_proxy=http://192.168.40.1:3128 &&
export https_proxy=$http_proxy &&
export ftp_proxy=$http_proxy &&
export rsync_proxy=$http_proxy &&
export no_proxy="localhost,127.0.0.1,localaddress,.udec.cl"
export HTTP_PROXY=$http_proxy &&
export HTTPS_PROXY=$http_proxy &&
export FTP_PROXY=$http_proxy &&
export RSYNC_PROXY=$http_proxy &&
export NO_PROXY=$no_proxy &&
sudo cp 95proxies /etc/apt/apt.conf.d/95proxies
